from aoc.day07 import solve_part1, solve_part2

input_data = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""


def test_solve_part1():
    assert solve_part1(input_data) == 21


def test_solve_part2():
    assert solve_part2(input_data) == 40
